id = "PLUTO"
name = "PLUTO Language Support"
version = "0.1.0"
schema_version = 1
authors = ["s7g4"]
description = "A lightweight, expressive syntax for scripting with full syntax highlighting and parsing support for Zed using Tree-sitter"
repository = "https://github.com/s7g4/tree-sitter-pluto"

[grammars.pluto]
repository = "https://github.com/s7g4/tree-sitter-pluto"
rev = "c1705d023e9202b21f1631549519166301c6109b"
