name = "Pluto"
grammar = "pluto"
path_suffixes = ["pluto"]
line_comments = ["# "]
autoclose_before = ")]}:.,=; \t\n"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
